# Generated by Django 5.2.4 on 2025-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(help_text="Stores the document's unique identifier", primary_key=True, serialize=False)),
                ('type', models.TextField(help_text='Stores the document type, credit report, or loan agreement', max_length=50)),
                ('file_url', models.ImageField(help_text='Stores the URL of the file', upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Stores the time the document was uploaded')),
            ],
        ),
    ]
