# Generated by Django 5.2.4 on 2025-07-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_repayments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='total_outstanding_loan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
