# Generated by Django 5.2.4 on 2025-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativePartnerBank',
            fields=[
                ('bank_partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=40)),
                ('bank_account_number', models.CharField(max_length=20)),
                ('amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateTimeField()),
                ('amount_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
