# Generated by Django 5.2.4 on 2025-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerWealth',
            fields=[
                ('farmer_wealth_id', models.AutoField(primary_key=True, serialize=False)),
                ('milk_quantity', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
