# Generated by Django 5.2.4 on 2025-07-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_wealth', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerwealth',
            name='livestock_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmerwealth',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmerwealth',
            name='milk_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
