# Generated by Django 5.2.4 on 2025-07-26 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_wealth', '0003_farmerwealth_livestock_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerwealth',
            name='livestock_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
