# Generated by Django 5.2.4 on 2025-07-26 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_wealth', '0004_alter_farmerwealth_livestock_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerwealth',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wealth_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
